#!/usr/bin/env python3
"""Regenerate the process numbers from the repository itself.

    python3 research/case-study/scripts/process-record.py [--tex record.tex]

Writes a markdown summary to stdout and, with --tex, LaTeX macros for the process record. The rule that
every number comes from a script applies to the record of the process too: days, commits, errata,
fallacies and readings are counted here, never typed.

Nothing here is an achievement metric. Commits per day measure activity, not progress, and a programme
with 200 commits and no adversarial reading is in worse shape than one with 20 and three.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
RESEARCH = ROOT / "research"


def git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True,
                              timeout=30).stdout
    except Exception:
        return ""


def read(p: Path) -> str:
    return p.read_text(errors="replace") if p.is_file() else ""


def collect() -> dict:
    log = [l for l in git("log", "--date=short", "--pretty=%ad").splitlines() if l.strip()]
    per_day = Counter(log)
    knowledge = read(RESEARCH / "KNOWLEDGE.md")
    errata = read(RESEARCH / "ERRATA.md")

    fallacies = sorted({int(m) for m in re.findall(r"^\s*\**F(\d+)\.", knowledge, re.M)})
    # an item is "**12. Paper I, Theorem 3**" (optionally quoted); a numbered rule list is not an item
    errata_items = sorted({int(m) for m in re.findall(r"^\s*>?\s*\*\*(\d+)\.", errata, re.M)})
    reviews = sorted(p.name for p in (RESEARCH / "reviews").glob("*")
                     if p.is_file() and p.name != "README.md")
    docs = sorted(p.name for p in RESEARCH.glob("*") if p.is_dir() and (p / "main.tex").is_file())

    pages = {}
    for d in docs:
        pdf = RESEARCH / d / "main.pdf"
        if pdf.is_file():
            try:
                out = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True, timeout=20)
                m = re.search(r"^Pages:\s+(\d+)", out.stdout, re.M)
                if m:
                    pages[d] = int(m.group(1))
            except Exception:
                pass

    return {
        "commits": len(log),
        "days": len(per_day),
        "first_day": min(per_day) if per_day else "—",
        "last_day": max(per_day) if per_day else "—",
        "busiest_day": max(per_day.items(), key=lambda kv: kv[1]) if per_day else ("—", 0),
        "per_day": dict(sorted(per_day.items())),
        "fallacies": fallacies,
        "errata": errata_items,
        "reviews": reviews,
        "documents": docs,
        "pages": pages,
    }


def markdown(d: dict) -> str:
    L = ["# Process record (generated)", "",
         f"- commits: **{d['commits']}** over **{d['days']}** active days "
         f"({d['first_day']} – {d['last_day']})",
         f"- busiest day: {d['busiest_day'][0]} with {d['busiest_day'][1]} commits",
         f"- documents with a `main.tex`: {len(d['documents'])} "
         f"({', '.join(d['documents']) or 'none'})",
         f"- pages: {', '.join(f'{k} {v}' for k, v in d['pages'].items()) or 'nothing compiled'}",
         f"- recorded fallacies: **{len(d['fallacies'])}** "
         f"(F1–F{max(d['fallacies'])})" if d["fallacies"] else "- recorded fallacies: **0** "
         "— either nothing has gone wrong yet, or nothing is being written down",
         f"- errata items: **{len(d['errata'])}**",
         f"- archived outside readings: **{len(d['reviews'])}**"
         + (f" ({', '.join(d['reviews'])})" if d["reviews"] else " — nobody outside the sessions has read this yet"),
         "", "## Commits per day", "", "| day | commits |", "|---|---|"]
    L += [f"| {day} | {n} |" for day, n in d["per_day"].items()]
    return "\n".join(L) + "\n"


def tex(d: dict) -> str:
    def macro(name: str, value) -> str:
        return f"\\newcommand{{\\{name}}}{{{value}}}\n"
    out = "% Generated by research/case-study/scripts/process-record.py — do not edit.\n"
    out += macro("NCommits", d["commits"])
    out += macro("NDays", d["days"])
    out += macro("FirstDay", d["first_day"])
    out += macro("LastDay", d["last_day"])
    out += macro("NFallacies", len(d["fallacies"]))
    out += macro("NErrata", len(d["errata"]))
    out += macro("NReviews", len(d["reviews"]))
    out += macro("NDocuments", len(d["documents"]))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tex", nargs="?", const="record.tex", default=None,
                    help="also write LaTeX macros to this file (default record.tex)")
    args = ap.parse_args()
    d = collect()
    sys.stdout.write(markdown(d))
    if args.tex:
        target = Path(args.tex)
        if not target.is_absolute():
            target = Path(__file__).resolve().parent.parent / target
        target.write_text(tex(d))
        print(f"\nwrote {target}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
