#!/usr/bin/env python3
"""Extract the quantitative process record of the Ulam-nD programme from the repository itself.

Writes record.tex (LaTeX macros + a commits-per-day table) next to main.tex. Every number in the case study
that describes the process comes from here, so that `python3 scripts/process-record.py` regenerates them.
Run from anywhere inside the repository.
"""
import subprocess, re, os, collections, glob
root = subprocess.check_output(['git','rev-parse','--show-toplevel'], text=True).strip()
os.chdir(root)
def git(*a): return subprocess.check_output(['git',*a], text=True)
log = git('log','--reverse','--format=%ad%x09%s','--date=format:%Y-%m-%d %H:%M').splitlines()
days = collections.OrderedDict()
for l in log:
    d = l.split('\t')[0][:10]; days[d] = days.get(d,0)+1
first, last = log[0][:10], log[-1][:10]
ncommits = len(log)
rev = git('rev-parse','--short','HEAD').strip()
# pages per paper from the compiled PDFs (pdfinfo), fallback to '?'
def pages(pdf):
    try:
        out = subprocess.check_output(['pdfinfo',pdf], text=True); return re.search(r'Pages:\s+(\d+)',out).group(1)
    except Exception: return '?'
papers = {k: pages(f'research/paper-{k}/main.pdf') for k in ['I','II','III','IV']}
kn = open('research/KNOWLEDGE.md', encoding='utf-8').read()
er = open('research/ERRATA.md', encoding='utf-8').read()
nfall = len(re.findall(r'^F\d+\.', kn, re.M))
nerr = max(int(x) for x in re.findall(r'^(\d+)\. \*\*', er, re.M))
nts = len(glob.glob('research/**/scripts/*.ts', recursive=True)) + len(glob.glob('research/experiments/*.ts')) + len(glob.glob('research/lib/*.ts'))
npy = len(glob.glob('research/**/*.py', recursive=True))
ndata = len(glob.glob('research/**/data/*', recursive=True)) + len(glob.glob('research/experiments/*.json'))
nreviews = len(glob.glob('research/reviews/*.pdf'))
texlines = sum(len(open(f'research/paper-{k}/main.tex', encoding='utf-8').read().splitlines()) for k in papers)
with open('research/case-study/record.tex','w', encoding='utf-8') as f:
    f.write('%% generated by scripts/process-record.py -- do not edit\n')
    f.write(f'\\newcommand{{\\NCommits}}{{{ncommits}}}\n\\newcommand{{\\FirstDay}}{{{first}}}\n\\newcommand{{\\LastDay}}{{{last}}}\n')
    f.write(f'\\newcommand{{\\NDays}}{{{len(days)}}}\n\\newcommand{{\\NFallacies}}{{{nfall}}}\n\\newcommand{{\\NErrata}}{{{nerr}}}\n')
    f.write(f'\\newcommand{{\\NScriptsTS}}{{{nts}}}\n\\newcommand{{\\NScriptsPy}}{{{npy}}}\n\\newcommand{{\\NData}}{{{ndata}}}\n')
    f.write(f'\\newcommand{{\\NReviews}}{{{nreviews}}}\n\\newcommand{{\\NTexLines}}{{{texlines}}}\n')
    f.write(f'\\newcommand{{\\RepoRev}}{{{rev}}}\n')
    for k,v in papers.items(): f.write(f'\\newcommand{{\\Pages{k}}}{{{v}}}\n')
    f.write('\\newcommand{\\CommitsTable}{\\begin{tabular}{lr}\\toprule day & commits\\\\\\midrule\n')
    for d,n in days.items(): f.write(f'{d} & {n}\\\\\n')
    f.write('\\bottomrule\\end{tabular}}\n')
print(f'{ncommits} commits over {len(days)} days ({first} .. {last}); fallacies {nfall}, errata {nerr}; pages {papers}')
