#!/usr/bin/env python3
"""Generate research/paper-II/data/wp0.tex from research/paper-II/data/explicit-diag.json (never edit numbers in main.tex)."""
import json
d = json.load(open("research/paper-II/data/explicit-diag.json"))
m2, m3 = d["per_m"]["2"], d["per_m"]["3"]
lines = [
    r"\providecommand{\wpDfone}{%.10f}" % d["Df1"],
    r"\providecommand{\wpC}{%.12f}" % d["C"],
    r"\providecommand{\wpBeta}{%.3f}" % m2["beta"],
    r"\providecommand{\wpBetaThree}{%.3f}" % m3["beta"],
    r"\providecommand{\wpBetaNuis}{%.3f}" % m2["beta_nuis"],
    r"\providecommand{\wpBetaNuisThree}{%.3f}" % m3["beta_nuis"],
    r"\providecommand{\wpRtwo}{%.2f}" % m2["R2_nuis"],
    r"\providecommand{\wpRtwoThree}{%.2f}" % m3["R2_nuis"],
    r"\providecommand{\wpBetaZeta}{%.3f}" % m2["per_family_beta"]["zeta k=2"],
    r"\providecommand{\wpBetaL}{%.3f}" % m2["per_family_beta"]["L k=2"],
    r"\providecommand{\wpRmsResid}{%.3f}" % m2["rms_resid"],
    r"\providecommand{\wpRmsLeft}{%.3f}" % m2["rms_left_nuis"],
    r"\providecommand{\wpNZ}{%d}" % d["nZ"],
    r"\providecommand{\wpNL}{%d}" % d["nL"],
]
open("research/paper-II/data/wp0.tex", "w").write("% generated by scripts/gen-wp0.py\n" + "\n".join(lines) + "\n")
print("\n".join(lines))
