import PairSingularSeries
-- Run `lake env lean Axioms.lean`: every line must show only [propext, Classical.choice, Quot.sound].
#print axioms PairSingularSeries.class_eq_image
#print axioms PairSingularSeries.floor_eq
#print axioms PairSingularSeries.B_closed
#print axioms PairSingularSeries.phi_bounds
#print axioms PairSingularSeries.B_diag
#print axioms PairSingularSeries.bracket_eq
#print axioms PairSingularSeries.bracket_abs_le
#print axioms PairSingularSeries.dvd_eval_iff
#print axioms PairSingularSeries.filter_range_dvd_eq_singleton
#print axioms PairSingularSeries.sum_roots_indicator
#print axioms PairSingularSeries.sum_weight_nu
#print axioms PairSingularSeries.sum_nu
#print axioms PairSingularSeries.psi_zero
#print axioms PairSingularSeries.sum_nu_weighted
#print axioms PairSingularSeries.Tfac_eq
#print axioms PairSingularSeries.card_filter_crt
#print axioms PairSingularSeries.omega_mul
#print axioms PairSingularSeries.nu_mul
#print axioms PairSingularSeries.cf_mul
#print axioms PairSingularSeries.cf_prime
#print axioms PairSingularSeries.bfun_mul
#print axioms PairSingularSeries.Fterm_mul
#print axioms PairSingularSeries.Fterm_prime
#print axioms PairSingularSeries.Fterm_prime_pow
#print axioms PairSingularSeries.omega_eq_card_zmod
#print axioms PairSingularSeries.omega_le_natDegree
#print axioms PairSingularSeries.summable_abs_of_squarefree_mult
#print axioms PairSingularSeries.sum_range_abs_le_prod
#print axioms PairSingularSeries.abs_gfac_le
#print axioms PairSingularSeries.summable_gabs
#print axioms PairSingularSeries.summable_abs_Fterm
#print axioms PairSingularSeries.tsum_Fterm_pow
#print axioms PairSingularSeries.Spartial_eq
#print axioms PairSingularSeries.tendsto_prod_one_add_gfac
#print axioms PairSingularSeries.expansion
#print axioms PairSingularSeries.sum_weight_cf
#print axioms PairSingularSeries.sum_moebius_divisors
#print axioms PairSingularSeries.sum_antidiag_Gterm
#print axioms PairSingularSeries.nu_ne_zero_dvd
#print axioms PairSingularSeries.summable_abs_Aterm
#print axioms PairSingularSeries.summable_abs_Bterm
#print axioms PairSingularSeries.tsum_sum_divisorsAntidiagonal
#print axioms PairSingularSeries.tsum_Bd
#print axioms PairSingularSeries.weighted_identity
#print axioms PairSingularSeries.Sf_eq
#print axioms PairSingularSeries.eq_identity
#print axioms PairSingularSeries.eq_smoothed_exact
